### ISSUE TITLE
Unable to load country flags

### ISSUE THREAD

**Issue by warulerahul** [vanshg395/intl_phone_field#46]
Unable to load asset: packages/intl_phone_field/assets/flags/in.png

**Comment by vanshg395** [comment]
Can you please elaborate the issue? Mention your flutter version, package version you are using?

**Comment by melisaBeysumengu** [comment]
I am having the same issue. 

This is the error:

`======== Exception caught by image resource service ================================================
The following assertion was thrown resolving an image codec:
Unable to load asset: packages/intl_phone_field/assets/flags/us.png

When the exception was thrown, this was the stack: 
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:227:7)
<asynchronous suspension>
#1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:667:14)
<asynchronous suspension>
Image provider: AssetImage(bundle: null, name: "packages/intl_phone_field/assets/flags/us.png")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#c9ce3(), name: "packages/intl_phone_field/assets/flags/us.png", scale: 1.0)
====================================================================================================

======== Exception caught by image resource service ================================================
The following assertion was thrown resolving an image codec:
Unable to load asset: packages/intl_phone_field/assets/flags/af.png

When the exception was thrown, this was the stack: 
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:227:7)
<asynchronous suspension>
#1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:667:14)
<asynchronous suspension>
Image provider: AssetImage(bundle: null, name: "packages/intl_phone_field/assets/flags/af.png")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#c9ce3(), name: "packages/intl_phone_field/assets/flags/af.png", scale: 1.0)
====================================================================================================

======== Exception caught by image resource service ================================================
Unable to load asset: packages/intl_phone_field/assets/flags/ax.png
====================================================================================================

======== Exception caught by image resource service ================================================
Unable to load asset: packages/intl_phone_field/assets/flags/al.png
====================================================================================================
.
.
.this goes for all the flags.
.
`

flutter doctor:
`Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19041.804], locale tr-TR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.54.1)
[√] Connected device (2 available)

• No issues found!
`

everything works fine beside the icons.  I copy pasted your code in the example section.

**Comment by devanshu89w** [comment]
copy the assets/flags folder inside your project's assets folder and add the following entry in pubspec.yaml 

    - assets/flags/

**Comment by vanshg395** [comment]
@melisaBeysumengu is the issue fixed from the solution from @devanshu89w? If it still exists, can you demonstrate how are you using the flags? Try to put up the code snippet where you have used it.

**Comment by vanshg395** [comment]
Fixed in #52

**Comment by DionJChapman** [comment]
I am still having this issue when deploying to Firebase host, but not the local Chrome

I am sure I am not generating the assets correctly, but it doesn't even seem to be calling the images.

**Comment by DionJChapman** [comment]
These may need to change. Once I removed these images and use fluttergen, it will work fine (missing these images). Can you prefix/suffix the names so this doesn't happen?

line 201, column 29 of .: 'do' can't be used as an identifier because it's a keyword.
    ╷
201 │           AssetGenImage get do => const AssetGenImage('assets/flags/do.png');
    │                             ^^
    ╵
line 348, column 29 of .: 'in' can't be used as an identifier because it's a keyword.
    ╷
348 │           AssetGenImage get in => const AssetGenImage('assets/flags/in.png');
    │                             ^^
    ╵
line 360, column 29 of .: 'is' can't be used as an identifier because it's a keyword.
    ╷
360 │           AssetGenImage get is => const AssetGenImage('assets/flags/is.png');
    │                             ^^
    ╵
